version: "3.8"

services:
  todo-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev # Use the development target (the Node.js environment)
    container_name: todo-frontend
    ports:
      - "5173:5173" # Vite development server port
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:3000 # Backend URL for development
    command: npm run dev # Start the Vite development server
    working_dir: /app
