services:
  # Frontend service
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
      target: dev
    container_name: todo-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./todo-frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    command: npm run dev
    working_dir: /app
    networks:
      - todo-network

  # Backend services
  todo-backend:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: server
    networks:
      - todo-network

  mongo:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: mongo
    networks:
      - todo-network

  redis:
    extends:
      file: ./todo-backend/docker-compose.dev.yml
      service: redis
    networks:
      - todo-network

  # Nginx reverse proxy
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    container_name: reverse-proxy
    depends_on:
      - todo-frontend
      - todo-backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data:
