version: "3.8"

services:
  # Frontend service
  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
      target: dev
    container_name: todo-frontend
    ports:
      - "5173:5173" # Map Vite's default dev port
    volumes:
      - ./todo-frontend:/app # Mount the frontend source code
      - /app/node_modules # Anonymous volume for node_modules
    environment:
      - VITE_BACKEND_URL=http://todo-backend:3000
    command: npm run dev # Start the frontend dev server
    working_dir: /app # Set working directory inside container
    networks:
      - todo-network

  # Nginx reverse proxy
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro # Mount custom Nginx config
    ports:
      - "8080:80" # Expose Nginx on port 8080
    container_name: reverse-proxy
    depends_on:
      - todo-frontend # Wait for frontend container to be up
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
