version: "3.8"

services:
  # MongoDB service
  mongo:
    image: mongo
    ports:
      - "3456:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  # Redis service
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  # Backend server service
  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: todo-backend
    volumes:
      - .:/usr/src/app # Mount the local source code directory
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database?retryWrites=false
    depends_on:
      - mongo
      - redis

volumes:
  mongo_data:
  redis_data:
